default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
development:
  <<: *default
  database: moviebox_development
test:
  <<: *default
  database: moviebox_test
production:
  <<: *default
  database: moviebox_production
  username: moviebox
  password: <%= ENV["MOVIEBOX_DATABASE_PASSWORD"] %>
  